name: CI with Gradle

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle 설정
        uses: gradle/actions/setup-gradle@v3

      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.DB_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      - name: Gradle TEST
        run: ./gradlew test
        env:
          DB_URL: DB URL = ${{ secrets.DB_URL }}
          DB_USER_NAME: USER = ${{ secrets.DB_USER_NAME }}
          DB_PASSWORD: PSW = ${{ secrets.DB_PASSWORD }}


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: JDK 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: dependency graph 생성 및 제출
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0